name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
    - name: Run make command
      run: make hello install lint test
